/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.api;

import de.dfki.cos.basys.common.rest.camunda.*;
import de.dfki.cos.basys.common.rest.camunda.auth.*;
import de.dfki.cos.basys.common.rest.camunda.dto.CountResultDto;
import de.dfki.cos.basys.common.rest.camunda.dto.ExceptionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.IncidentDto;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IncidentApi
 */
public class IncidentApiTest {

    private final IncidentApi api = new IncidentApi();

    /**
     * Get Incident
     *
     * Retrieves an incident by ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIncidentTest() throws ApiException {
        //String id = null;
        //IncidentDto response = api.getIncident(id);
        // TODO: test validations
    }

    /**
     * Get List
     *
     * Queries for incidents that fulfill given parameters. The size of the result set can be retrieved by using the [Get Incident Count](https://docs.camunda.org/manual/7.14/reference/rest/incident/get-query-count/) method.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIncidentsTest() throws ApiException {
        //String incidentId = null;
        //String incidentType = null;
        //String incidentMessage = null;
        //String incidentMessageLike = null;
        //String processDefinitionId = null;
        //String processDefinitionKeyIn = null;
        //String processInstanceId = null;
        //String executionId = null;
        //OffsetDateTime incidentTimestampBefore = null;
        //OffsetDateTime incidentTimestampAfter = null;
        //String activityId = null;
        //String failedActivityId = null;
        //String causeIncidentId = null;
        //String rootCauseIncidentId = null;
        //String _configuration = null;
        //String tenantIdIn = null;
        //String jobDefinitionIdIn = null;
        //String sortBy = null;
        //String sortOrder = null;
        //List<IncidentDto> response = api.getIncidents(incidentId, incidentType, incidentMessage, incidentMessageLike, processDefinitionId, processDefinitionKeyIn, processInstanceId, executionId, incidentTimestampBefore, incidentTimestampAfter, activityId, failedActivityId, causeIncidentId, rootCauseIncidentId, _configuration, tenantIdIn, jobDefinitionIdIn, sortBy, sortOrder);
        // TODO: test validations
    }

    /**
     * Get List Count
     *
     * Queries for the number of incidents that fulfill given parameters. Takes the same parameters as the [Get Incidents](https://docs.camunda.org/manual/7.14/reference/rest/incident/get-query/) method.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getIncidentsCountTest() throws ApiException {
        //String incidentId = null;
        //String incidentType = null;
        //String incidentMessage = null;
        //String incidentMessageLike = null;
        //String processDefinitionId = null;
        //String processDefinitionKeyIn = null;
        //String processInstanceId = null;
        //String executionId = null;
        //OffsetDateTime incidentTimestampBefore = null;
        //OffsetDateTime incidentTimestampAfter = null;
        //String activityId = null;
        //String failedActivityId = null;
        //String causeIncidentId = null;
        //String rootCauseIncidentId = null;
        //String _configuration = null;
        //String tenantIdIn = null;
        //String jobDefinitionIdIn = null;
        //List<CountResultDto> response = api.getIncidentsCount(incidentId, incidentType, incidentMessage, incidentMessageLike, processDefinitionId, processDefinitionKeyIn, processInstanceId, executionId, incidentTimestampBefore, incidentTimestampAfter, activityId, failedActivityId, causeIncidentId, rootCauseIncidentId, _configuration, tenantIdIn, jobDefinitionIdIn);
        // TODO: test validations
    }

    /**
     * Resolve Incident
     *
     * Resolves an incident with given id.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void resolveIncidentTest() throws ApiException {
        //String id = null;
        //api.resolveIncident(id);
        // TODO: test validations
    }

}
