/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.api;

import de.dfki.cos.basys.common.rest.camunda.*;
import de.dfki.cos.basys.common.rest.camunda.auth.*;
import de.dfki.cos.basys.common.rest.camunda.dto.VersionDto;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VersionApi
 */
public class VersionApiTest {

    private final VersionApi api = new VersionApi();

    /**
     * 
     *
     * Retrieves the version of the Rest API.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRestAPIVersionTest() throws ApiException {
        //VersionDto response = api.getRestAPIVersion();
        // TODO: test validations
    }

}
