/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AbstractSetRemovalTimeDto
 */
public class AbstractSetRemovalTimeDtoTest {
    private final AbstractSetRemovalTimeDto model = new AbstractSetRemovalTimeDto();

    /**
     * Model tests for AbstractSetRemovalTimeDto
     */
    @Test
    public void testAbstractSetRemovalTimeDto() {
        // TODO: test AbstractSetRemovalTimeDto
    }

    /**
     * Test the property 'absoluteRemovalTime'
     */
    @Test
    public void absoluteRemovalTimeTest() {
        // TODO: test absoluteRemovalTime
    }

    /**
     * Test the property 'clearedRemovalTime'
     */
    @Test
    public void clearedRemovalTimeTest() {
        // TODO: test clearedRemovalTime
    }

    /**
     * Test the property 'calculatedRemovalTime'
     */
    @Test
    public void calculatedRemovalTimeTest() {
        // TODO: test calculatedRemovalTime
    }

}
