/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.dfki.cos.basys.common.rest.camunda.dto.HistoricProcessInstanceQueryDto;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessInstanceQueryDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeleteProcessInstancesDto
 */
public class DeleteProcessInstancesDtoTest {
    private final DeleteProcessInstancesDto model = new DeleteProcessInstancesDto();

    /**
     * Model tests for DeleteProcessInstancesDto
     */
    @Test
    public void testDeleteProcessInstancesDto() {
        // TODO: test DeleteProcessInstancesDto
    }

    /**
     * Test the property 'processInstanceIds'
     */
    @Test
    public void processInstanceIdsTest() {
        // TODO: test processInstanceIds
    }

    /**
     * Test the property 'deleteReason'
     */
    @Test
    public void deleteReasonTest() {
        // TODO: test deleteReason
    }

    /**
     * Test the property 'skipCustomListeners'
     */
    @Test
    public void skipCustomListenersTest() {
        // TODO: test skipCustomListeners
    }

    /**
     * Test the property 'skipSubprocesses'
     */
    @Test
    public void skipSubprocessesTest() {
        // TODO: test skipSubprocesses
    }

    /**
     * Test the property 'processInstanceQuery'
     */
    @Test
    public void processInstanceQueryTest() {
        // TODO: test processInstanceQuery
    }

    /**
     * Test the property 'historicProcessInstanceQuery'
     */
    @Test
    public void historicProcessInstanceQueryTest() {
        // TODO: test historicProcessInstanceQuery
    }

}
