/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.dfki.cos.basys.common.rest.camunda.dto.AbstractSetRemovalTimeDto;
import de.dfki.cos.basys.common.rest.camunda.dto.HistoricProcessInstanceQueryDto;
import de.dfki.cos.basys.common.rest.camunda.dto.SetRemovalTimeToHistoricProcessInstancesDtoAllOf;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetRemovalTimeToHistoricProcessInstancesDto
 */
public class SetRemovalTimeToHistoricProcessInstancesDtoTest {
    private final SetRemovalTimeToHistoricProcessInstancesDto model = new SetRemovalTimeToHistoricProcessInstancesDto();

    /**
     * Model tests for SetRemovalTimeToHistoricProcessInstancesDto
     */
    @Test
    public void testSetRemovalTimeToHistoricProcessInstancesDto() {
        // TODO: test SetRemovalTimeToHistoricProcessInstancesDto
    }

    /**
     * Test the property 'historicProcessInstanceIds'
     */
    @Test
    public void historicProcessInstanceIdsTest() {
        // TODO: test historicProcessInstanceIds
    }

    /**
     * Test the property 'historicProcessInstanceQuery'
     */
    @Test
    public void historicProcessInstanceQueryTest() {
        // TODO: test historicProcessInstanceQuery
    }

    /**
     * Test the property 'hierarchical'
     */
    @Test
    public void hierarchicalTest() {
        // TODO: test hierarchical
    }

    /**
     * Test the property 'absoluteRemovalTime'
     */
    @Test
    public void absoluteRemovalTimeTest() {
        // TODO: test absoluteRemovalTime
    }

    /**
     * Test the property 'clearedRemovalTime'
     */
    @Test
    public void clearedRemovalTimeTest() {
        // TODO: test clearedRemovalTime
    }

    /**
     * Test the property 'calculatedRemovalTime'
     */
    @Test
    public void calculatedRemovalTimeTest() {
        // TODO: test calculatedRemovalTime
    }

}
