/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessInstanceModificationInstructionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.VariableValueDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for StartProcessInstanceDto
 */
public class StartProcessInstanceDtoTest {
    private final StartProcessInstanceDto model = new StartProcessInstanceDto();

    /**
     * Model tests for StartProcessInstanceDto
     */
    @Test
    public void testStartProcessInstanceDto() {
        // TODO: test StartProcessInstanceDto
    }

    /**
     * Test the property 'businessKey'
     */
    @Test
    public void businessKeyTest() {
        // TODO: test businessKey
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'caseInstanceId'
     */
    @Test
    public void caseInstanceIdTest() {
        // TODO: test caseInstanceId
    }

    /**
     * Test the property 'startInstructions'
     */
    @Test
    public void startInstructionsTest() {
        // TODO: test startInstructions
    }

    /**
     * Test the property 'skipCustomListeners'
     */
    @Test
    public void skipCustomListenersTest() {
        // TODO: test skipCustomListeners
    }

    /**
     * Test the property 'skipIoMappings'
     */
    @Test
    public void skipIoMappingsTest() {
        // TODO: test skipIoMappings
    }

    /**
     * Test the property 'withVariablesInReturn'
     */
    @Test
    public void withVariablesInReturnTest() {
        // TODO: test withVariablesInReturn
    }

}
