include:
    - project: i40/administration
      file: gitlab-ci-maven.yml
      ref: main

variables:
  MVN_FORBID_SNAPSHOT_DEPENDENCIES_DISABLED : "true"
  MAVEN_DEPLOY_FROM_UNPROTECTED_DISABLED: "true"
  MAVEN_DEPLOY_ENABLED: "true"
