/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import de.dfki.cos.basys.common.rest.camunda.JSON;


/**
 * ProblemDto
 */
@JsonPropertyOrder({
  ProblemDto.JSON_PROPERTY_MESSAGE,
  ProblemDto.JSON_PROPERTY_LINE,
  ProblemDto.JSON_PROPERTY_COLUMN,
  ProblemDto.JSON_PROPERTY_MAIN_ELEMENT_ID,
  ProblemDto.JSON_PROPERTY_ELEMENT_IDS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-11T21:54:35.456Z[GMT]")
public class ProblemDto {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;

  public static final String JSON_PROPERTY_LINE = "line";
  private JsonNullable<Integer> line = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_COLUMN = "column";
  private JsonNullable<Integer> column = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_MAIN_ELEMENT_ID = "mainElementId";
  private String mainElementId;

  public static final String JSON_PROPERTY_ELEMENT_IDS = "elementIds";
  private List<String> elementIds = null;


  public ProblemDto message(String message) {
    this.message = message;
    return this;
  }

   /**
   * The message of the problem.
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The message of the problem.")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ProblemDto line(Integer line) {
    this.line = JsonNullable.<Integer>of(line);
    return this;
  }

   /**
   * The line where the problem occurred.
   * @return line
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The line where the problem occurred.")
  @JsonIgnore

  public Integer getLine() {
        return line.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getLine_JsonNullable() {
    return line;
  }
  
  @JsonProperty(JSON_PROPERTY_LINE)
  public void setLine_JsonNullable(JsonNullable<Integer> line) {
    this.line = line;
  }

  public void setLine(Integer line) {
    this.line = JsonNullable.<Integer>of(line);
  }


  public ProblemDto column(Integer column) {
    this.column = JsonNullable.<Integer>of(column);
    return this;
  }

   /**
   * The column where the problem occurred.
   * @return column
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The column where the problem occurred.")
  @JsonIgnore

  public Integer getColumn() {
        return column.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COLUMN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getColumn_JsonNullable() {
    return column;
  }
  
  @JsonProperty(JSON_PROPERTY_COLUMN)
  public void setColumn_JsonNullable(JsonNullable<Integer> column) {
    this.column = column;
  }

  public void setColumn(Integer column) {
    this.column = JsonNullable.<Integer>of(column);
  }


  public ProblemDto mainElementId(String mainElementId) {
    this.mainElementId = mainElementId;
    return this;
  }

   /**
   * The main element id where the problem occurred.
   * @return mainElementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The main element id where the problem occurred.")
  @JsonProperty(JSON_PROPERTY_MAIN_ELEMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMainElementId() {
    return mainElementId;
  }


  public void setMainElementId(String mainElementId) {
    this.mainElementId = mainElementId;
  }


  public ProblemDto elementIds(List<String> elementIds) {
    this.elementIds = elementIds;
    return this;
  }

  public ProblemDto addElementIdsItem(String elementIdsItem) {
    if (this.elementIds == null) {
      this.elementIds = new ArrayList<String>();
    }
    this.elementIds.add(elementIdsItem);
    return this;
  }

   /**
   * A list of element id affected by the problem.
   * @return elementIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of element id affected by the problem.")
  @JsonProperty(JSON_PROPERTY_ELEMENT_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getElementIds() {
    return elementIds;
  }


  public void setElementIds(List<String> elementIds) {
    this.elementIds = elementIds;
  }


  /**
   * Return true if this ProblemDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProblemDto problemDto = (ProblemDto) o;
    return Objects.equals(this.message, problemDto.message) &&
        Objects.equals(this.line, problemDto.line) &&
        Objects.equals(this.column, problemDto.column) &&
        Objects.equals(this.mainElementId, problemDto.mainElementId) &&
        Objects.equals(this.elementIds, problemDto.elementIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, line, column, mainElementId, elementIds);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProblemDto {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    line: ").append(toIndentedString(line)).append("\n");
    sb.append("    column: ").append(toIndentedString(column)).append("\n");
    sb.append("    mainElementId: ").append(toIndentedString(mainElementId)).append("\n");
    sb.append("    elementIds: ").append(toIndentedString(elementIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

