/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import de.dfki.cos.basys.common.rest.camunda.JSON;


/**
 * UserCredentialsDto
 */
@JsonPropertyOrder({
  UserCredentialsDto.JSON_PROPERTY_PASSWORD,
  UserCredentialsDto.JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-03-11T21:54:35.456Z[GMT]")
public class UserCredentialsDto {
  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD = "authenticatedUserPassword";
  private String authenticatedUserPassword;


  public UserCredentialsDto password(String password) {
    this.password = password;
    return this;
  }

   /**
   * The users new password.
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The users new password.")
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public UserCredentialsDto authenticatedUserPassword(String authenticatedUserPassword) {
    this.authenticatedUserPassword = authenticatedUserPassword;
    return this;
  }

   /**
   * The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter).
   * @return authenticatedUserPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter).")
  @JsonProperty(JSON_PROPERTY_AUTHENTICATED_USER_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAuthenticatedUserPassword() {
    return authenticatedUserPassword;
  }


  public void setAuthenticatedUserPassword(String authenticatedUserPassword) {
    this.authenticatedUserPassword = authenticatedUserPassword;
  }


  /**
   * Return true if this UserCredentialsDto object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCredentialsDto userCredentialsDto = (UserCredentialsDto) o;
    return Objects.equals(this.password, userCredentialsDto.password) &&
        Objects.equals(this.authenticatedUserPassword, userCredentialsDto.authenticatedUserPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, authenticatedUserPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCredentialsDto {\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    authenticatedUserPassword: ").append(toIndentedString(authenticatedUserPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

