/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.AtomLink;
import de.dfki.cos.basys.common.rest.camunda.dto.CaseDefinitionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.DecisionDefinitionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.DecisionRequirementsDefinitionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.DeploymentDto;
import de.dfki.cos.basys.common.rest.camunda.dto.DeploymentWithDefinitionsDtoAllOf;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessDefinitionDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeploymentWithDefinitionsDto
 */
public class DeploymentWithDefinitionsDtoTest {
    private final DeploymentWithDefinitionsDto model = new DeploymentWithDefinitionsDto();

    /**
     * Model tests for DeploymentWithDefinitionsDto
     */
    @Test
    public void testDeploymentWithDefinitionsDto() {
        // TODO: test DeploymentWithDefinitionsDto
    }

    /**
     * Test the property 'deployedProcessDefinitions'
     */
    @Test
    public void deployedProcessDefinitionsTest() {
        // TODO: test deployedProcessDefinitions
    }

    /**
     * Test the property 'deployedDecisionDefinitions'
     */
    @Test
    public void deployedDecisionDefinitionsTest() {
        // TODO: test deployedDecisionDefinitions
    }

    /**
     * Test the property 'deployedDecisionRequirementsDefinitions'
     */
    @Test
    public void deployedDecisionRequirementsDefinitionsTest() {
        // TODO: test deployedDecisionRequirementsDefinitions
    }

    /**
     * Test the property 'deployedCaseDefinitions'
     */
    @Test
    public void deployedCaseDefinitionsTest() {
        // TODO: test deployedCaseDefinitions
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'deploymentTime'
     */
    @Test
    public void deploymentTimeTest() {
        // TODO: test deploymentTime
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
