/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.CaseDefinitionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.DecisionDefinitionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.DecisionRequirementsDefinitionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessDefinitionDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DeploymentWithDefinitionsDtoAllOf
 */
public class DeploymentWithDefinitionsDtoAllOfTest {
    private final DeploymentWithDefinitionsDtoAllOf model = new DeploymentWithDefinitionsDtoAllOf();

    /**
     * Model tests for DeploymentWithDefinitionsDtoAllOf
     */
    @Test
    public void testDeploymentWithDefinitionsDtoAllOf() {
        // TODO: test DeploymentWithDefinitionsDtoAllOf
    }

    /**
     * Test the property 'deployedProcessDefinitions'
     */
    @Test
    public void deployedProcessDefinitionsTest() {
        // TODO: test deployedProcessDefinitions
    }

    /**
     * Test the property 'deployedDecisionDefinitions'
     */
    @Test
    public void deployedDecisionDefinitionsTest() {
        // TODO: test deployedDecisionDefinitions
    }

    /**
     * Test the property 'deployedDecisionRequirementsDefinitions'
     */
    @Test
    public void deployedDecisionRequirementsDefinitionsTest() {
        // TODO: test deployedDecisionRequirementsDefinitions
    }

    /**
     * Test the property 'deployedCaseDefinitions'
     */
    @Test
    public void deployedCaseDefinitionsTest() {
        // TODO: test deployedCaseDefinitions
    }

}
