/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.FetchExternalTaskTopicDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FetchExternalTasksDto
 */
public class FetchExternalTasksDtoTest {
    private final FetchExternalTasksDto model = new FetchExternalTasksDto();

    /**
     * Model tests for FetchExternalTasksDto
     */
    @Test
    public void testFetchExternalTasksDto() {
        // TODO: test FetchExternalTasksDto
    }

    /**
     * Test the property 'workerId'
     */
    @Test
    public void workerIdTest() {
        // TODO: test workerId
    }

    /**
     * Test the property 'maxTasks'
     */
    @Test
    public void maxTasksTest() {
        // TODO: test maxTasks
    }

    /**
     * Test the property 'usePriority'
     */
    @Test
    public void usePriorityTest() {
        // TODO: test usePriority
    }

    /**
     * Test the property 'asyncResponseTimeout'
     */
    @Test
    public void asyncResponseTimeoutTest() {
        // TODO: test asyncResponseTimeout
    }

    /**
     * Test the property 'topics'
     */
    @Test
    public void topicsTest() {
        // TODO: test topics
    }

}
