/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HistoricActivityInstanceDto
 */
public class HistoricActivityInstanceDtoTest {
    private final HistoricActivityInstanceDto model = new HistoricActivityInstanceDto();

    /**
     * Model tests for HistoricActivityInstanceDto
     */
    @Test
    public void testHistoricActivityInstanceDto() {
        // TODO: test HistoricActivityInstanceDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'parentActivityInstanceId'
     */
    @Test
    public void parentActivityInstanceIdTest() {
        // TODO: test parentActivityInstanceId
    }

    /**
     * Test the property 'activityId'
     */
    @Test
    public void activityIdTest() {
        // TODO: test activityId
    }

    /**
     * Test the property 'activityName'
     */
    @Test
    public void activityNameTest() {
        // TODO: test activityName
    }

    /**
     * Test the property 'activityType'
     */
    @Test
    public void activityTypeTest() {
        // TODO: test activityType
    }

    /**
     * Test the property 'processDefinitionKey'
     */
    @Test
    public void processDefinitionKeyTest() {
        // TODO: test processDefinitionKey
    }

    /**
     * Test the property 'processDefinitionId'
     */
    @Test
    public void processDefinitionIdTest() {
        // TODO: test processDefinitionId
    }

    /**
     * Test the property 'processInstanceId'
     */
    @Test
    public void processInstanceIdTest() {
        // TODO: test processInstanceId
    }

    /**
     * Test the property 'executionId'
     */
    @Test
    public void executionIdTest() {
        // TODO: test executionId
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'assignee'
     */
    @Test
    public void assigneeTest() {
        // TODO: test assignee
    }

    /**
     * Test the property 'calledProcessInstanceId'
     */
    @Test
    public void calledProcessInstanceIdTest() {
        // TODO: test calledProcessInstanceId
    }

    /**
     * Test the property 'calledCaseInstanceId'
     */
    @Test
    public void calledCaseInstanceIdTest() {
        // TODO: test calledCaseInstanceId
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'durationInMillis'
     */
    @Test
    public void durationInMillisTest() {
        // TODO: test durationInMillis
    }

    /**
     * Test the property 'canceled'
     */
    @Test
    public void canceledTest() {
        // TODO: test canceled
    }

    /**
     * Test the property 'completeScope'
     */
    @Test
    public void completeScopeTest() {
        // TODO: test completeScope
    }

    /**
     * Test the property 'tenantId'
     */
    @Test
    public void tenantIdTest() {
        // TODO: test tenantId
    }

    /**
     * Test the property 'removalTime'
     */
    @Test
    public void removalTimeTest() {
        // TODO: test removalTime
    }

    /**
     * Test the property 'rootProcessInstanceId'
     */
    @Test
    public void rootProcessInstanceIdTest() {
        // TODO: test rootProcessInstanceId
    }

}
