/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for MissingAuthorizationDto
 */
public class MissingAuthorizationDtoTest {
    private final MissingAuthorizationDto model = new MissingAuthorizationDto();

    /**
     * Model tests for MissingAuthorizationDto
     */
    @Test
    public void testMissingAuthorizationDto() {
        // TODO: test MissingAuthorizationDto
    }

    /**
     * Test the property 'permissionName'
     */
    @Test
    public void permissionNameTest() {
        // TODO: test permissionName
    }

    /**
     * Test the property 'resourceName'
     */
    @Test
    public void resourceNameTest() {
        // TODO: test resourceName
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

}
