/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.TriggerVariableValueDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessInstanceModificationInstructionDto
 */
public class ProcessInstanceModificationInstructionDtoTest {
    private final ProcessInstanceModificationInstructionDto model = new ProcessInstanceModificationInstructionDto();

    /**
     * Model tests for ProcessInstanceModificationInstructionDto
     */
    @Test
    public void testProcessInstanceModificationInstructionDto() {
        // TODO: test ProcessInstanceModificationInstructionDto
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'activityId'
     */
    @Test
    public void activityIdTest() {
        // TODO: test activityId
    }

    /**
     * Test the property 'transitionId'
     */
    @Test
    public void transitionIdTest() {
        // TODO: test transitionId
    }

    /**
     * Test the property 'activityInstanceId'
     */
    @Test
    public void activityInstanceIdTest() {
        // TODO: test activityInstanceId
    }

    /**
     * Test the property 'transitionInstanceId'
     */
    @Test
    public void transitionInstanceIdTest() {
        // TODO: test transitionInstanceId
    }

    /**
     * Test the property 'ancestorActivityInstanceId'
     */
    @Test
    public void ancestorActivityInstanceIdTest() {
        // TODO: test ancestorActivityInstanceId
    }

    /**
     * Test the property 'cancelCurrentActiveActivityInstances'
     */
    @Test
    public void cancelCurrentActiveActivityInstancesTest() {
        // TODO: test cancelCurrentActiveActivityInstances
    }

}
