/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessInstanceModificationInstructionDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProcessInstanceModificationDto
 */
public class ProcessInstanceModificationDtoTest {
    private final ProcessInstanceModificationDto model = new ProcessInstanceModificationDto();

    /**
     * Model tests for ProcessInstanceModificationDto
     */
    @Test
    public void testProcessInstanceModificationDto() {
        // TODO: test ProcessInstanceModificationDto
    }

    /**
     * Test the property 'skipCustomListeners'
     */
    @Test
    public void skipCustomListenersTest() {
        // TODO: test skipCustomListeners
    }

    /**
     * Test the property 'skipIoMappings'
     */
    @Test
    public void skipIoMappingsTest() {
        // TODO: test skipIoMappings
    }

    /**
     * Test the property 'instructions'
     */
    @Test
    public void instructionsTest() {
        // TODO: test instructions
    }

    /**
     * Test the property 'annotation'
     */
    @Test
    public void annotationTest() {
        // TODO: test annotation
    }

}
