/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.HistoricProcessInstanceQueryDto;
import de.dfki.cos.basys.common.rest.camunda.dto.RestartProcessInstanceModificationInstructionDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RestartProcessInstanceDto
 */
public class RestartProcessInstanceDtoTest {
    private final RestartProcessInstanceDto model = new RestartProcessInstanceDto();

    /**
     * Model tests for RestartProcessInstanceDto
     */
    @Test
    public void testRestartProcessInstanceDto() {
        // TODO: test RestartProcessInstanceDto
    }

    /**
     * Test the property 'processInstanceIds'
     */
    @Test
    public void processInstanceIdsTest() {
        // TODO: test processInstanceIds
    }

    /**
     * Test the property 'historicProcessInstanceQuery'
     */
    @Test
    public void historicProcessInstanceQueryTest() {
        // TODO: test historicProcessInstanceQuery
    }

    /**
     * Test the property 'skipCustomListeners'
     */
    @Test
    public void skipCustomListenersTest() {
        // TODO: test skipCustomListeners
    }

    /**
     * Test the property 'skipIoMappings'
     */
    @Test
    public void skipIoMappingsTest() {
        // TODO: test skipIoMappings
    }

    /**
     * Test the property 'initialVariables'
     */
    @Test
    public void initialVariablesTest() {
        // TODO: test initialVariables
    }

    /**
     * Test the property 'withoutBusinessKey'
     */
    @Test
    public void withoutBusinessKeyTest() {
        // TODO: test withoutBusinessKey
    }

    /**
     * Test the property 'instructions'
     */
    @Test
    public void instructionsTest() {
        // TODO: test instructions
    }

}
