/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.dfki.cos.basys.common.rest.camunda.dto.ExternalTaskQueryDto;
import de.dfki.cos.basys.common.rest.camunda.dto.HistoricProcessInstanceQueryDto;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessInstanceQueryDto;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SetRetriesForExternalTasksDto
 */
public class SetRetriesForExternalTasksDtoTest {
    private final SetRetriesForExternalTasksDto model = new SetRetriesForExternalTasksDto();

    /**
     * Model tests for SetRetriesForExternalTasksDto
     */
    @Test
    public void testSetRetriesForExternalTasksDto() {
        // TODO: test SetRetriesForExternalTasksDto
    }

    /**
     * Test the property 'retries'
     */
    @Test
    public void retriesTest() {
        // TODO: test retries
    }

    /**
     * Test the property 'externalTaskIds'
     */
    @Test
    public void externalTaskIdsTest() {
        // TODO: test externalTaskIds
    }

    /**
     * Test the property 'processInstanceIds'
     */
    @Test
    public void processInstanceIdsTest() {
        // TODO: test processInstanceIds
    }

    /**
     * Test the property 'externalTaskQuery'
     */
    @Test
    public void externalTaskQueryTest() {
        // TODO: test externalTaskQuery
    }

    /**
     * Test the property 'processInstanceQuery'
     */
    @Test
    public void processInstanceQueryTest() {
        // TODO: test processInstanceQuery
    }

    /**
     * Test the property 'historicProcessInstanceQuery'
     */
    @Test
    public void historicProcessInstanceQueryTest() {
        // TODO: test historicProcessInstanceQuery
    }

}
