/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.api;

import de.dfki.cos.basys.common.rest.camunda.ApiException;
import de.dfki.cos.basys.common.rest.camunda.dto.ProcessEngineDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EngineApi
 */
@Ignore
public class EngineApiTest {

    private final EngineApi api = new EngineApi();

    
    /**
     * 
     *
     * Retrieves the names of all process engines available on your platform. **Note**: You cannot prepend &#x60;/engine/{name}&#x60; to this method.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProcessEngineNamesTest() throws ApiException {
        List<ProcessEngineDto> response = api.getProcessEngineNames();

        // TODO: test validations
    }
    
}
