/*
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.dfki.cos.basys.common.rest.camunda.api;

import de.dfki.cos.basys.common.rest.camunda.ApiException;
import de.dfki.cos.basys.common.rest.camunda.dto.ExceptionDto;
import de.dfki.cos.basys.common.rest.camunda.dto.MetricsIntervalResultDto;
import de.dfki.cos.basys.common.rest.camunda.dto.MetricsResultDto;
import org.threeten.bp.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetricsApi
 */
@Ignore
public class MetricsApiTest {

    private final MetricsApi api = new MetricsApi();

    
    /**
     * 
     *
     * Retrieves the &#x60;sum&#x60; (count) for a given metric.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMetricsTest() throws ApiException {
        String metricsName = null;
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        MetricsResultDto response = api.getMetrics(metricsName, startDate, endDate);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves a list of metrics, aggregated for a given interval.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void intervalTest() throws ApiException {
        String name = null;
        String reporter = null;
        OffsetDateTime startDate = null;
        OffsetDateTime endDate = null;
        Integer firstResult = null;
        Integer maxResults = null;
        String interval = null;
        String aggregateByReporter = null;
        List<MetricsIntervalResultDto> response = api.interval(name, reporter, startDate, endDate, firstResult, maxResults, interval, aggregateByReporter);

        // TODO: test validations
    }
    
}
